d /var/opt/virtual-space-trotting 0755 root root -
d /var/opt/virtual-space-trotting/mpulse 0755 root root -
d /var/opt/virtual-space-trotting/mpulse/public 0750 root caddy -
d /var/opt/virtual-space-trotting/mpulse/state 0750 root vst-mpulse-operators -
d /var/opt/virtual-space-trotting/mpulse/state/registry-backups 0750 root vst-mpulse-operators -
